# Exercises: Functions

### Introduction to functions

Write a function named `addone` that adds 1 to its input.

In [ ]:
function addone(x)
    return x + 1
end

In [2]:
addone(1)

2

In [1]:
addone([1,2,3])

3-element Array{Int64,1}:
 2
 3
 4

### Polynomial

Write your own 2nd order polynomial function `poly2(x)` that evaluates $4 + 3x + 2x^2$.

In [11]:
poly2(x) = 4 + 3x + 2x^2

poly2 (generic function with 1 method)

In [12]:
poly2(1)

9

Abstractify your function a little to take `x` and `coeffs` as an input. `coeffs` should be an array of length `3` that holds the coefficients of the polynomial. Internally your function should then compute $C_3 x^2 + C_2 x + C_1$ where $C_i$ is the $i$th element of the `coeff` array.

In [13]:
function poly2(x, coeffs)
    @assert length(coeffs) == 3

    y = 0
    for i in 1:3
        y += coeffs[i] * x^(i-1)
    end
    return y
end

poly2 (generic function with 2 methods)

In [14]:
poly2(1, [4,3,2])

9

**Advanced**: Can you generalize your function to work for any $n$th order polynomial of the form $C_{n+1} x^{n} + C_{n} x^{n-1} \ldots C_{n+1} x + C_n$ ?

In [16]:
function poly(x, coeffs)
    y = 0
    for i in 1:length(coeffs)
        y += coeffs[i] * x^(i-1)
    end
    return y
end

poly (generic function with 1 method)

### Map / Broadcast

Use `map` or `broadcast` to increment every element of a matrix `A` by `1` using the function defined in the first exercise.

You can easily create an empty matrix for testing with `A = zeros(5,5)`.

In [8]:
A = zeros(5,5)

map(addone, A)

5×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

### Dot syntax

Try out the broadcast dot syntax to increment every element of matrix `A` by `1` using the function defined in the first exercise.

In [9]:
addone.(A)

5×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

### Advanced: More dots
Generalize the previous polynomial function to work for matrices, too. In practise this means that `x` can be of array too and the polynomial function is evaluated for every element of that array.

In [1]:
function poly(x, coeffs)
    y = zeros(x)
    for i in 1:length(coeffs)
        y .+= coeffs[i] .* x.^(i-1)
    end
    return y
end

poly (generic function with 1 method)

In [2]:
x = ones(4,4)
coeffs = [4,3,2]
poly(x, coeffs)

4×4 Array{Float64,2}:
 9.0  9.0  9.0  9.0
 9.0  9.0  9.0  9.0
 9.0  9.0  9.0  9.0
 9.0  9.0  9.0  9.0